import type { Metadata } from "next";
import { Gideon_Roman } from "next/font/google";
import "./globals.css";

const gideonRoman = Gideon_Roman({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-gideonRoman",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={gideonRoman.className}>{children}</body>
    </html>
  );
}
