import type { Metadata } from "next";
import { Gideon_Roman, Lora } from "next/font/google";

import "./globals.css";

const gideonRoman = Gideon_Roman({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-gideonRoman",
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-lora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gideonRoman.variable} ${lora.variable} font-lora`}>
        {children}
      </body>
    </html>
  );
}
